/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coin {
  'owner' : Principal,
  'metadata' : [] | [string],
  'name' : string,
  'description' : string,
  'totalSupply' : bigint,
  'symbol' : string,
}
export interface MarketCapTrendPoint {
  'marketCap' : bigint,
  'timestamp' : Time,
}
export interface Order {
  'coinSymbol' : string,
  'side' : OrderSide,
  'user' : Principal,
  'orderId' : bigint,
  'timestamp' : Time,
  'quantity' : bigint,
  'price' : number,
}
export type OrderSide = { 'buy' : null } |
  { 'sell' : null };
export interface PricePoint { 'timestamp' : Time, 'price' : number }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeWithdrawal' : ActorMethod<[string, bigint], undefined>,
  'createCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createStripeSession' : ActorMethod<[string, bigint], undefined>,
  'finalizeDeposit' : ActorMethod<[string], undefined>,
  'getBalance' : ActorMethod<[string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreatorCapRanking' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getCreatorCoinsWithMarketCaps' : ActorMethod<
    [],
    Array<[Principal, Array<Coin>, bigint]>
  >,
  'getMarketCapTrend' : ActorMethod<[Principal], Array<MarketCapTrendPoint>>,
  'getOrderBook' : ActorMethod<
    [string, OrderSide, [] | [bigint]],
    Array<Order>
  >,
  'getPriceHistory' : ActorMethod<[string, [] | [bigint]], Array<PricePoint>>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeMarketOrder' : ActorMethod<[string, OrderSide, bigint], bigint>,
  'placeOrder' : ActorMethod<[string, OrderSide, number, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];