/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Coin = IDL.Record({
  'owner' : IDL.Principal,
  'metadata' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const Time = IDL.Int;
export const MarketCapTrendPoint = IDL.Record({
  'marketCap' : IDL.Nat,
  'timestamp' : Time,
});
export const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Order = IDL.Record({
  'coinSymbol' : IDL.Text,
  'side' : OrderSide,
  'user' : IDL.Principal,
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const PricePoint = IDL.Record({
  'timestamp' : Time,
  'price' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeWithdrawal' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createStripeSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'finalizeDeposit' : IDL.Func([IDL.Text], [], []),
  'getBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreatorCapRanking' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getCreatorCoinsWithMarketCaps' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Coin), IDL.Nat))],
      ['query'],
    ),
  'getMarketCapTrend' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MarketCapTrendPoint)],
      ['query'],
    ),
  'getOrderBook' : IDL.Func(
      [IDL.Text, OrderSide, IDL.Opt(IDL.Nat)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getPriceHistory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(PricePoint)],
      ['query'],
    ),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeMarketOrder' : IDL.Func([IDL.Text, OrderSide, IDL.Nat], [IDL.Nat], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, OrderSide, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Coin = IDL.Record({
    'owner' : IDL.Principal,
    'metadata' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const Time = IDL.Int;
  const MarketCapTrendPoint = IDL.Record({
    'marketCap' : IDL.Nat,
    'timestamp' : Time,
  });
  const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Order = IDL.Record({
    'coinSymbol' : IDL.Text,
    'side' : OrderSide,
    'user' : IDL.Principal,
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const PricePoint = IDL.Record({ 'timestamp' : Time, 'price' : IDL.Float64 });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeWithdrawal' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createStripeSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'finalizeDeposit' : IDL.Func([IDL.Text], [], []),
    'getBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreatorCapRanking' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getCreatorCoinsWithMarketCaps' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(Coin), IDL.Nat))],
        ['query'],
      ),
    'getMarketCapTrend' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MarketCapTrendPoint)],
        ['query'],
      ),
    'getOrderBook' : IDL.Func(
        [IDL.Text, OrderSide, IDL.Opt(IDL.Nat)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getPriceHistory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(PricePoint)],
        ['query'],
      ),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeMarketOrder' : IDL.Func(
        [IDL.Text, OrderSide, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'placeOrder' : IDL.Func(
        [IDL.Text, OrderSide, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };