/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
});
export const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Time = IDL.Int;
export const Order = IDL.Record({
  'coinSymbol' : IDL.Text,
  'side' : OrderSide,
  'user' : IDL.Principal,
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'getBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderBook' : IDL.Func(
      [IDL.Text, OrderSide, IDL.Opt(IDL.Nat)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, OrderSide, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
  });
  const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'coinSymbol' : IDL.Text,
    'side' : OrderSide,
    'user' : IDL.Principal,
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'getBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderBook' : IDL.Func(
        [IDL.Text, OrderSide, IDL.Opt(IDL.Nat)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, OrderSide, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };